# Use the official Golang image as the base image
FROM golang:1.17-alpine AS builder

# Set the current working directory inside the container
WORKDIR /app

# Copy the Go modules files
COPY go.mod ./
COPY go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go application
RUN go build -o consumer-app consumer.go

# Use a minimal Alpine image for the final stage
FROM alpine:latest

# Set the working directory to /root
WORKDIR /root

# Copy the binary built in the previous stage
COPY --from=builder /app/consumer-app .

# Command to run the executable
CMD ["./consumer-app"]
