apiVersion: v1
kind: Service
metadata:
  name: consumer-chart
  labels:
    app.kubernetes.io/name: consumer-chart
    helm.sh/chart: consumer-chart-0.1.0
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: consumer-chart
    app.kubernetes.io/instance: my-release
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

