apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-chart
  labels:
    app.kubernetes.io/name: producer-chart
    helm.sh/chart: producer-chart-0.1.0
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: producer-chart
      app.kubernetes.io/instance: my-release
  template:
    metadata:
      labels:
        app.kubernetes.io/name: producer-chart
        app.kubernetes.io/instance: my-release
    spec:
      containers:
        - name: producer-chart
          image: "producer-app:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
